# Generated by Django 5.2 on 2025-05-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_fooditem_remove_review_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.fooditem'),
        ),
    ]
