# Generated by Django 5.2 on 2025-05-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_fooditem_remove_review_item_name_review_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='food_item',
        ),
    ]
